const HIRAGANA = [
  {ro:'a', char:'あ'}, 
  {ro:'i', char:'い'}, 
  {ro:'u', char:'う'}, 
  {ro:'e', char:'え'},
  {ro:'o', char:'お'},
  {ro:'ka', char:'か'}, 
  {ro:'ki', char:'き'}, 
  {ro:'ku', char:'く'}, 
  {ro:'ke', char:'け'}, 
  {ro:'ko', char:'こ'}, 
  {ro:'sa', char:'さ'}, 
  {ro:'shi', char:'し'}, 
  {ro:'su', char:'す'}, 
  {ro:'se', char:'せ'}, 
  {ro:'so', char:'そ'}, 
  {ro:'ta', char:'た'}, 
  {ro:'chi', char:'ち'}, 
  {ro:'tsu', char:'つ'}, 
  {ro:'te', char:'て'}, 
  {ro:'to', char:'と'}, 
  {ro:'na', char:'な'}, 
  {ro:'ni', char:'に'}, 
  {ro:'nu', char:'ぬ'}, 
  {ro:'ne', char:'ね'}, 
  {ro:'no', char:'の'}, 
  {ro:'ha', char:'は'}, 
  {ro:'hi', char:'ひ'}, 
  {ro:'fu', char:'ふ'}, 
  {ro:'he', char:'へ'},
  {ro:'ho', char:'ほ'}, 
  {ro:'ma', char:'ま'}, 
  {ro:'mi', char:'み'}, 
  {ro:'mu', char:'む'}, 
  {ro:'me', char:'め'}, 
  {ro:'mo', char:'も'}, 
  {ro:'ya', char:'や'}, 
  {ro:'yu', char:'ゆ'}, 
  {ro:'yo', char:'よ'}, 
  {ro:'ra', char:'ら'}, 
  {ro:'ri', char:'り'}, 
  {ro:'ru', char:'る'}, 
  {ro:'re', char:'れ'}, 
  {ro:'ro', char:'ろ'}, 
  {ro:'wa', char:'わ'}, 
  {ro:'wo', char:'を'}, 
  {ro:'n',char:'ん'}
];

function choice() {
  return HIRAGANA[Math.floor(Math.random() * HIRAGANA.length)];
}

export { HIRAGANA, choice };